# Generated by Django 3.1 on 2020-08-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_pub',
        ),
    ]
